// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BookBorrowing.API.Models
{
    public partial class Book
    {
        [Key]
        [Column("idBook")]
        public int IdBook { get; set; }
        [Column("bookName")]
        [StringLength(100)]
        public string BookName { get; set; }
        [Column("authorName")]
        [StringLength(150)]
        public string AuthorName { get; set; }
        [Required]
        [Column("publisherName")]
        [StringLength(10)]
        public string PublisherName { get; set; }
        [Column("publisherDate", TypeName = "date")]
        public DateTime? PublisherDate { get; set; }
        [Column("bookEdition")]
        [StringLength(30)]
        [Unicode(false)]
        public string BookEdition { get; set; }
        [Column("bookImg")]
        [Unicode(false)]
        public string BookImg { get; set; }
    }
}